services:
  app:
    build:
      context: .
      dockerfile: docker/ruby/Dockerfile
    command: ./bin/dev
    volumes:
      - ./src:/src
    ports:
      - "3000:3000"
    tty: true
  db:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
volumes:
  db:
